### ISSUE TITLE
Getting error when generating BMI genetic score

### ISSUE THREAD

**Issue by yang654** [MRCIEU/PHESANT-MR-pheWAS-BMI#1]
Hey,
Thanks for developing PHEASANT-MR-pheWAS-BMI which is a very useful tool.  I tried to generate BMI genetic score following the script in the file "1-BMI-genetic-score". It runs fine in the first two steps. I came across some problems in the third step. I don't know what's the file "ukb7341.enc_ukb". I also wonder the form of the output file "SNP-score97-withPhenIds.csv", Your help will be greatly appreciated! Thanks a lot.

**Comment by AineDuffy** [comment]
Hi, just wondering did you ever solve this @yang654 ? Have come across the same problem. Thanks!!

**Comment by louise** [comment]
Afraid this isn't a 'tool' it's a record of the code I used to conduct my own MR-pheWAS in UK Biobank. 

enc_ukb files are data files provided by UK Biobank, see here https://biobank.ctsu.ox.ac.uk/crystal/exinfo.cgi?src=accessing_data_guide

The SNP-score97-withPhenIds.csv file contains the 97 SNPs, the BMI genetic risk score and the phenotypic IDs – this step was needed because the genetic and phenotype data have different IDs with a linker file used to map them together. I use the phenotype IDs so needed to add them to the SNP/GRS genetic data I needed to use.

Hope that helps.
